# -*- coding: utf-8 -*-
"""Balsara_final_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRVotp67CwNUkXlFDuoCo2WKukVIPuLK
"""

!pip install numpy scikit-learn

"""Load Images into Co-Lab"""

from PIL import Image
import numpy as np

#function used to download images from data folder
def load_data(image_path):
  img=Image.open(image_path)
  #change image size for faster processing
  img=img.resize((200,200))
  return np.array(img)

import os
from IPython.display import display
images=[]
data_path='./' #path from co lab

for file in os.listdir(data_path):
  #only jpgs will be uploaded
  image_path= os.path.join(data_path, file)
  image= load_data(image_path)
  images.append(image)

display(images[0])
loaded_data=load_data(data_path)

def flatten_image(image):
  return image.reshape((-1, image.shape[-1]))
  #flatten 3D array representing image (width, height, RGB channels into 2D array (pixels x RGB channels))
  #information for this code found at https://www.geeksforgeeks.org/impact-of-image-flattening/